# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/simple_arm/simple_arm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm || ORIG_REF_NAME==simple_arm} -quiet] -quiet

# IP: bd/simple_arm/ip/simple_arm_processing_system7_0_0/simple_arm_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm_processing_system7_0_0 || ORIG_REF_NAME==simple_arm_processing_system7_0_0} -quiet] -quiet

# IP: bd/simple_arm/ip/simple_arm_axi_gpio_0_0/simple_arm_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm_axi_gpio_0_0 || ORIG_REF_NAME==simple_arm_axi_gpio_0_0} -quiet] -quiet

# IP: bd/simple_arm/ip/simple_arm_xbar_0/simple_arm_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm_xbar_0 || ORIG_REF_NAME==simple_arm_xbar_0} -quiet] -quiet

# IP: bd/simple_arm/ip/simple_arm_ps7_0_axi_periph_0/simple_arm_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm_ps7_0_axi_periph_0 || ORIG_REF_NAME==simple_arm_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/simple_arm/ip/simple_arm_rst_ps7_0_100M_0/simple_arm_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm_rst_ps7_0_100M_0 || ORIG_REF_NAME==simple_arm_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/simple_arm/ip/simple_arm_axi_gpio_0_1/simple_arm_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm_axi_gpio_0_1 || ORIG_REF_NAME==simple_arm_axi_gpio_0_1} -quiet] -quiet

# IP: bd/simple_arm/ip/simple_arm_fpadd_ip_0_0/simple_arm_fpadd_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm_fpadd_ip_0_0 || ORIG_REF_NAME==simple_arm_fpadd_ip_0_0} -quiet] -quiet

# IP: bd/simple_arm/ip/simple_arm_auto_pc_0/simple_arm_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_arm_auto_pc_0 || ORIG_REF_NAME==simple_arm_auto_pc_0} -quiet] -quiet

# XDC: /home/inf2020/gkapakos/Desktop/Embedded/labs/lab2/step3/fpadd_arm/fpadd_arm.gen/sources_1/bd/simple_arm/simple_arm_ooc.xdc
