# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/inf2020/gkapakos/Desktop/Embedded/labs/lab2/step3/fpadd_arm/fpadd_arm.srcs/sources_1/bd/simple_arm/ip/simple_arm_xbar_0/simple_arm_xbar_0.xci
# IP: The module: 'simple_arm_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/inf2020/gkapakos/Desktop/Embedded/labs/lab2/step3/fpadd_arm/fpadd_arm.gen/sources_1/bd/simple_arm/ip/simple_arm_xbar_0/simple_arm_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simple_arm_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/inf2020/gkapakos/Desktop/Embedded/labs/lab2/step3/fpadd_arm/fpadd_arm.srcs/sources_1/bd/simple_arm/ip/simple_arm_xbar_0/simple_arm_xbar_0.xci
# IP: The module: 'simple_arm_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/inf2020/gkapakos/Desktop/Embedded/labs/lab2/step3/fpadd_arm/fpadd_arm.gen/sources_1/bd/simple_arm/ip/simple_arm_xbar_0/simple_arm_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simple_arm_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
